### ISSUE TITLE
Why 2021 tho?

### ISSUE THREAD

**Issue by macel94** [antoniosarosi/mkdb#1]
https://github.com/antoniosarosi/mkdb/blob/bf1341bc4da70971fc6c340f3a5e9c6bbc55da37/Cargo.toml#L4

**Comment by macel94** [comment]
my bad, i did not notice this is standard for rust and believed this was some kind of typo

**Comment by antoniosarosi** [comment]
The 2024 edition has not yet been released.

https://doc.rust-lang.org/edition-guide/rust-2024/index.html
